### ISSUE TITLE
Can't seem to get it to run

### ISSUE THREAD

**Issue by OJLMethos** [m2aadhil/gw2-autologin#1]
Hey,

I'm super interested in this Project but can't get it to function, wondering if I missed something?

1. I downloaded latest release
2. Set the game directory in the config.txt (for me, D:\Games\Guild Wars 2)
3.  entered email and password on lines per the example text
4. ran gw2autologin.exe

Nothing significant happens though. No error messages, no window appears.. .nothing.

any ideas?

**Comment by m2aadhil** [comment]
@OJLMethos may I know your windows version?

**Comment by OJLMethos** [comment]
@m2aadhil thanks for you reply!

I'm running:
Windows 10 home
version 10.0 build 19042

I do get an application very briefly pop up in the taskbar - so it's trying to do something but it instantly disappears without any error message.

**Comment by m2aadhil** [comment]
@OJLMethos Hi.. I will check on this issue and will give you an update EOD.

**Comment by m2aadhil** [comment]
@OJLMethos There was an issue with that Windows SDK was required to run the Application. It's resolved now. Could you download the latest build and verify.

**Comment by OJLMethos** [comment]
The application now runs! Nice

However it gets stuck on any account doesn't have SMS 2Factor Authentication on it... 
This is when it comes up with a "ready" screen instead of a "play" screen. and it cannot progress past that point.

**Comment by m2aadhil** [comment]
@OJLMethos Ahaa.. thank you for the suggestion.. I will look into that matter and try find a fix.. I'm gonna close this issue :).. you can create a new one for that :)
